### ISSUE TITLE
gradle support

### ISSUE THREAD

**Issue by QuadFlask** [JaeWoongOh/Android-Propose#2]

**Comment by muabe** [comment]
I will respond to all your comments in September 2015

Thank you

**Comment by QuadFlask** [comment]
You can use [Jitpack](https://jitpack.io/) until upload to jcenter

**Comment by muabe** [comment]
보니깐 다행히 한국분이시네요 ^^

Gradle을 접한지 얼마 안되서 repository 구성에 고민을 하고 있었는데
좋은 정보 정말 감사드립니다.
