### ISSUE TITLE
How to disable 3D-rotation in y-direction in the book?

### ISSUE THREAD

**Issue by lisizeilinger** [JaeWoongOh/Android-Propose#3]
Hi, the library works really nice. I have downloaded the storybook example and would like to know, how the 3D effect, when touching the book, can be disabled? I don't want it to be moved in y-direction.

**Comment by muabe** [comment]
Remove the instance of upDownMotoin in touchListener. 
It can disable y-direction.

Please code, as below.
- com.markjmind.propose.sample.estory.book.Book
- Book.java:243 Line 

``` java
pm.getPageLayout(dir).setOnTouchListener(new OnTouchListener() {
    @Override
    public boolean onTouch(View v, MotionEvent event) {
        motion.onTouch(v, event);
//      upDownMotoin.onTouch(v, event); //remove
        return true;
    }
});
```

**Comment by lisizeilinger** [comment]
Thanks, that worked!

**Comment by Plantaer** [comment]
Where can I find thist Book Sample?
