### ISSUE TITLE
How to implement cube viewpager use Propose

### ISSUE THREAD

**Issue by Rowandjj** [JaeWoongOh/Android-Propose#4]
https://www.youtube.com/watch?v=X0x4wgDQV20
is there any examples?

**Comment by muabe** [comment]
sorry 
I lost all the sample sources when migrating github
but I 'm making the sample in propose2
I hope to you waiting for propose2
thank you

**Comment by muabe** [comment]
hello 栗子

I lost all the sample sources when migrating github
but I 'm making the sample in propose2
I hope to you waiting for propose2
thank you

2017-07-06 12:44 GMT+09:00 栗子 <notifications@github.com>:

**Comment by muabe** [comment]
But it's easy

Use View.pipvot  before rotating in ObjectAnimator

good luck





2017-07-06 12:44 GMT+09:00 栗子 <notifications@github.com>:

**Comment by Rowandjj** [comment]
ok. i'll try that.thank you:)

BTW, when will you finish propose2? @muabe

**Comment by muabe** [comment]
Propose2 is planned to be completed by 2017.

Thank you for your interest.


2017-07-07 11:07 GMT+09:00 栗子 <notifications@github.com>:

**Comment by jaggi772** [comment]
@muabe i have tried to make animate like https://www.youtube.com/watch?v=X0x4wgDQV20 shown video but no success.  I need this type of animation. Plz help.

**Comment by muabe** [comment]
@jaggi772 I lost the sample sources. I don't have it now
If ObjectAnimator is available, you can implement it using the [view.pipvot](https://developer.android.com/reference/android/view/View.html#setPivotX(float)) method.
