### ISSUE TITLE
Sample request

### ISSUE THREAD

**Issue by Plantaer** [JaeWoongOh/Android-Propose#5]
I'm really excited about this library. More immersive apps is what i want to achieve. Could you please share with Cube Out Transform (https://www.youtube.com/watch?v=K_5Y16Fz0Ps) project or something similar? 

1. I don't understand how split one object (like circular ImageView on video) between left drawer and different Layout. How is it attached?

2. In Story Book on video (hadn't found sample code), how to transform only a half of Layout, View (whatever it is)? I mean page of the book.

Thank you in advance for your help.

**Comment by muabe** [comment]
English is not my first language.

미안하지만 정확한 설명을 위해서 모국어로 답변을 남김니다.

지금 Propose2.0을 개발중입니다.
그래서 이전에 있던 샘플들을 github에서 모두 삭제하고 2.0에 대한 샘플을 만드는 중입니다.

'Cube Out Transform' 을 하기위해서는 View.rotationY 와 View.setPivot를 사용하면 쉽게 구현할수
있습니다.

하지만 동영상을 보면 ImageView가 layout사이를 이동하고 있습니다. 애니메이션을 위한 Layout을 따로 만들었기 때문입니다.
또한 Propose2.0에서 해당 layout을 제공할것 입니다.

참고로 Propose2.0에서 더많은 모션/애니메이션과 Layout을 제공하려고합니다.
라이센스 또한 아파치로 변경할 예정입니다.
저는 늦어도 2017년도 안에 개발을 완료할것 계획입니다.(현재 70%)
원하신다면 개발이 완료되었을때 제일먼저 메일을 보내드리도록 하겠습니다.

조금만더 관심을 가지고 지켜봐주시면 감사하겠습니다.


2017-07-24 0:38 GMT+09:00 Plantaer <notifications@github.com>:

**Comment by Plantaer** [comment]
빠른 응답에 감사드립니다. 나는 Propose2.0에 대한 정보를 메일 (native1311@gmail.com)을 통해 얻고 싶다. Google이이를 전적으로 번역하기를 바랍니다. 행운을 빕니다.

**Comment by hpanahiird** [comment]
@muabe it 2018 and there is no propose 2.0 nor a single line of sample for propose 1. cube out transform in the way that you explained is not working on android 7.0 and above.

**Comment by muabe** [comment]
First of all, I would like to apologize for failing to keep our promise. I had been so busy lately that I was not able to finish developing. However, I’m currently working on the developing with other developers. So, please don’t worry. Our goal is to finish developing by end of this year. Again, I’m so sorry for not keeping the promise.
